### PR TITLE
Added unhook functionality

### PR DESCRIPTION
**Pull request by callumacrae**
I tried to stick to your coding standards, but I didn't realise understand them (do you use semi-colons or not?), so I've tried my best.

### CODE REVIEW

**Comment by callumacrae** [comment]
Bump! Can someone look at this? It's a pretty trivial change! :)

**Comment by KarlGl** [comment]
@jamesdavidson doesn't work here anymore and no one is maintaining this, so i'll just merge your change.

**Comment by callumacrae** [comment]
Thanks. It also needs a version bump and pushing to npm, though.

Would it make sense (and would you be okay with) if I took over this project? I can't see the point in forking it and changing the name slightly, there's enough packages on npm already.

It would involve adding me as a collaborator to this repo, and @jamesdavidson (or npm support) would need to add me as an owner to the package on npm.

Thanks!

**Comment by KarlGl** [comment]
Lol agreed, I just dropped him an email explaining what you just said. (jsdavo@gmail.com)

**Comment by callumacrae** [comment]
Awesome, cheers.

**Comment by jamesdavidson** [comment]
Hi Callum, it's all yours now. You should be able to fork and then npm-publish it.

**Comment by callumacrae** [comment]
Thanks!

**Pull request merged**
